fix AttributeError while using dsn-initialized connection
Actual error:
```
AttributeError
'ConnectionParameters' object has no attribute 'get'
```

where ConnectionParameters is a namedtuple object, that doesn't have "get" attribute.