Add test
Without the fix we have this in stdout:

[2024-10-28 12:14:18,868: ERROR/MainProcess] Failed to detach context
Traceback (most recent call last):
  File "/home/rm/src/opentelemetry-python-contrib/.tox/py310-test-instrumentation-celery-1/lib/python3.10/site-packages/opentelemetry/context/__init__.py", line 152, in detach
    _RUNTIME_CONTEXT.detach(token)
  File "/home/rm/src/opentelemetry-python-contrib/.tox/py310-test-instrumentation-celery-1/lib/python3.10/site-packages/opentelemetry/context/contextvars_context.py", line 50, in detach
    self._current_context.reset(token)  # type: ignore
TypeError: expected an instance of Token, got None