Fix doc error in file-level code block
The previous code example here was missing () so you get this if you try to use it:

  Traceback (most recent call last):
    File "./foo.py", line 37, in <module>
      RequestsInstrumentor.instrument()
  TypeError: instrument() missing 1 required positional argument: 'self'

This change makes the code example in this file function again. it also matches the code example in the opentelemetry-instrumentation-requests README.rst.